###
GET https://howtodoinjava.com/design-patterns/creational/builder-pattern-in-java/

###
GET https://docs.oracle.com/javase/tutorial/essential/concurrency/syncmeth.html

###
GET https://github.com/mrihtar/Treecapitator/blob/master/src/main/java/bspkrs/treecapitator/Treecapitator.java
